In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
type([1,2,3])

list

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a[0]

1

In [8]:
a[0] = 5

In [9]:
print(a)

[5 2 3 4]


In [18]:
b = np.array([[1,2,3],[5,6,7,]])
print(b)

[[1 2 3]
 [5 6 7]]


In [19]:
print(type(b))
print(b.shape)

<class 'numpy.ndarray'>
(2, 3)


In [20]:
print(b[0,0])

1


In [21]:
print(b[0])

[1 2 3]


In [22]:
print(b[:,0])

[1 5]


In [24]:
a = np.zeros((2,3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [25]:
c = np.full((2,3),9)
print(c)

[[9 9 9]
 [9 9 9]]


In [29]:
b = np.ones((2,2))
print(b)

[[ 1.  1.]
 [ 1.  1.]]


In [30]:
print(b[0])

[ 1.  1.]


In [31]:
d = np.eye(3)
print(d)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [33]:
e = np.random.random((3,4))
print(e)

[[ 0.29943691  0.48775029  0.64482698  0.1817556 ]
 [ 0.2988387   0.12165546  0.40694395  0.46307896]
 [ 0.31858226  0.67949368  0.38974399  0.54538911]]


In [34]:
f = np.empty((2,3,4))
print(f)

[[[  6.95162368e-310   4.66441381e-310   6.95159133e-310   2.18488538e-120]
  [  6.95159146e-310   6.95159133e-310   1.58812237e+037   6.95159146e-310]
  [  6.95159133e-310   1.07363123e-106   6.95162122e-310   6.95159146e-310]]

 [[ -1.42737681e-048   6.95159146e-310   6.95159146e-310   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]]]


In [36]:
g = np.arange(15)
print(g)
print(g.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


In [37]:
type((2,3))

tuple

In [38]:
arr = np.array([1,2,3])
print(arr.dtype)

int64


In [39]:
arr = np.array([1,2,3],dtype = np.float32)
print(arr.dtype)

float32


In [40]:
arr

array([ 1.,  2.,  3.], dtype=float32)

In [42]:
int_arr = np.array([1,2,3,4,5])
print(int_arr,int_arr.dtype)

[1 2 3 4 5] int64


In [43]:
float_arr = int_arr.astype(np.float)
print(float_arr.dtype,float_arr)

float64 [ 1.  2.  3.  4.  5.]


In [44]:
float_arr = np.array([3.4,2.3,4.7,-11.2])
print(float_arr)

[  3.4   2.3   4.7 -11.2]


In [50]:
int_arr = float_arr.astype(np.int16)
print(int_arr,int_arr.dtype)

[  3   2   4 -11] int16


In [58]:
str_arr = np.array(['1.22','2.2','5.6'],dtype = np.string_)
str_arr

array([b'1.22', b'2.2', b'5.6'],
      dtype='|S4')

In [59]:
float_arr = str_arr.astype(np.float)
float_arr

array([ 1.22,  2.2 ,  5.6 ])

In [60]:
print(float_arr)

[ 1.22  2.2   5.6 ]


In [61]:
int_arr = np.arange(10)
int_arr
float_arr = np.array([2.3,4.6,8.8])
float_arr
print(float_arr.dtype,int_arr.dtype)

float64 int64


In [65]:
int_arr.astype(dtype = float_arr.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [66]:
print(int_arr.dtype)

int64


In [81]:
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a = np.array(a)
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [82]:
b = a[0:2,2:4].copy()
print(b)

[[3 4]
 [7 8]]


In [83]:
b[0,0] = 123123
print(b)
print(a)

[[123123      4]
 [     7      8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [84]:
row_r1 = a[1,:]
print(row_r1,row_r1.shape)

[5 6 7 8] (4,)


In [86]:
row_r2 = a[1:2,:]%1:2表示的还是1这一行，不包括2
print(row_r2,row_r2.shape)

[[5 6 7 8]] (1, 4)


In [89]:
col_r1 = a[:,1]
print(col_r1)

[ 2  6 10]
