In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
type([1,2,3])

list

In [5]:
a

array([1, 2, 3, 4])

In [6]:
a[0]

1

In [7]:
a[0] = 5

In [8]:
print(a)

[5 2 3 4]


In [9]:
b = np.array([[1,2,3],[5,6,7,]])
print(b)

[[1 2 3]
 [5 6 7]]


In [10]:
print(type(b))
print(b.shape)

<class 'numpy.ndarray'>
(2, 3)


In [11]:
print(b[0,0])

1


In [12]:
print(b[0])

[1 2 3]


In [13]:
print(b[:,0])

[1 5]


In [14]:
a = np.zeros((2,3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [15]:
c = np.full((2,3),9)
print(c)

[[9 9 9]
 [9 9 9]]


In [16]:
b = np.ones((2,2))
print(b)

[[ 1.  1.]
 [ 1.  1.]]


In [17]:
print(b[0])

[ 1.  1.]


In [18]:
d = np.eye(3)
print(d)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [19]:
e = np.random.random((3,4))
print(e)

[[ 0.09555839  0.27870808  0.74584559  0.74579398]
 [ 0.7140396   0.30008852  0.69356755  0.43316722]
 [ 0.37837428  0.79660305  0.48102421  0.94675158]]


In [20]:
f = np.empty((2,3,4))
print(f)

[[[  6.92922974e-310   4.68285948e-310   6.92920081e-310   6.92920081e-310]
  [  4.68285880e-310   6.92920081e-310   6.92920080e-310   6.92920081e-310]
  [  6.92920081e-310   6.92920081e-310   6.92920081e-310   6.92920081e-310]]

 [[  6.92920081e-310   6.92920081e-310   6.92920081e-310   6.92922204e-310]
  [  6.92920081e-310   6.92920081e-310   6.92920081e-310   6.92922216e-310]
  [  6.92920081e-310   6.92922216e-310   6.92922204e-310   6.92922216e-310]]]


In [21]:
g = np.arange(15)
print(g)
print(g.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


In [22]:
type((2,3))

tuple

In [23]:
arr = np.array([1,2,3])
print(arr.dtype)

int64


In [24]:
arr = np.array([1,2,3],dtype = np.float32)
print(arr.dtype)

float32


In [25]:
arr

array([ 1.,  2.,  3.], dtype=float32)

In [26]:
int_arr = np.array([1,2,3,4,5])
print(int_arr,int_arr.dtype)

[1 2 3 4 5] int64


In [27]:
float_arr = int_arr.astype(np.float)
print(float_arr.dtype,float_arr)

float64 [ 1.  2.  3.  4.  5.]


In [28]:
float_arr = np.array([3.4,2.3,4.7,-11.2])
print(float_arr)

[  3.4   2.3   4.7 -11.2]


In [29]:
int_arr = float_arr.astype(np.int16)
print(int_arr,int_arr.dtype)

[  3   2   4 -11] int16


In [30]:
str_arr = np.array(['1.22','2.2','5.6'],dtype = np.string_)
str_arr

array([b'1.22', b'2.2', b'5.6'],
      dtype='|S4')

In [31]:
float_arr = str_arr.astype(np.float)
float_arr

array([ 1.22,  2.2 ,  5.6 ])

In [32]:
print(float_arr)

[ 1.22  2.2   5.6 ]


In [33]:
int_arr = np.arange(10)
int_arr
float_arr = np.array([2.3,4.6,8.8])
float_arr
print(float_arr.dtype,int_arr.dtype)

float64 int64


In [34]:
int_arr.astype(dtype = float_arr.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [35]:
print(int_arr.dtype)

int64


In [36]:
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a = np.array(a)
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [37]:
b = a[0:2,2:4].copy()
print(b)

[[3 4]
 [7 8]]


In [38]:
b[0,0] = 123123
print(b)
print(a)

[[123123      4]
 [     7      8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
row_r1 = a[1,:]
print(row_r1,row_r1.shape)

[5 6 7 8] (4,)


In [40]:
row_r2 = a[1:2,:]#1:2表示的还是1这一行，不包括2
print(row_r2,row_r2.shape)

[[5 6 7 8]] (1, 4)


In [41]:
col_r1 = a[:,1]
print(col_r1)

[ 2  6 10]


In [42]:
a = ['a','b','c'] + [1,2,3]
a

['a', 'b', 'c', 1, 2, 3]

In [43]:
type(a)

list

In [44]:
lambda x:x+1
type(lambda x:x+1)

function

In [45]:
#x**2 for x in range(10)

In [46]:
r = np.array(range(36))
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]


In [47]:
r = r.reshape(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [48]:
r[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [49]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [50]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [51]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [52]:
v = np.array([9,10])
w = np.array([10,11])
print(v)
print(v.shape)
print(w.shape)

[ 9 10]
(2,)
(2,)


In [53]:
x = v*w.T
print(x)
print(x.shape)

[ 90 110]
(2,)


In [54]:
v.dot(w)

200

In [55]:
np.dot(v,w)

200

In [56]:
v.dot(w)
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [57]:
v
print(x.dot(v))

[29 67]


In [58]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [59]:
x

array([[1, 2],
       [3, 4]])

In [60]:
x.T

array([[1, 3],
       [2, 4]])

In [61]:
v

array([ 9, 10])

In [62]:
print(x.dot(v))

[29 67]


In [63]:
v.T

array([ 9, 10])

In [64]:
v.shape

(2,)

In [65]:
w = np.array([[1,2,3]])
w

array([[1, 2, 3]])

In [66]:
print(w.T)

[[1]
 [2]
 [3]]


In [67]:
print(w.shape)

(1, 3)


In [68]:
arr = np.random.randn(6,3)
print(arr)

[[ 0.88715583 -1.29020386 -1.84776576]
 [ 1.01028443 -0.84771033  1.12310484]
 [-0.59206781 -0.36280263 -0.09229856]
 [-0.75897547 -0.46860847 -0.10713176]
 [-1.68878444  0.96319442  0.33939167]
 [ 0.0778165   1.03649356  0.61722668]]


In [69]:
print(arr.dot(arr.T))

[[ 5.86590979 -0.08523581  0.11337906  0.12922533 -3.36804843 -2.40874296]
 [-0.08523581  3.00065191 -0.39426631 -0.48985706 -2.14149006 -0.10681923]
 [ 0.11337906 -0.39426631  0.49068906  0.62926544  0.61910008 -0.47908437]
 [ 0.12922533 -0.48985706  0.62926544  0.80711489  0.79402528 -0.61089506]
 [-3.36804843 -2.14149006  0.61910008  0.79402528  3.89492309  1.07641111]
 [-2.40874296 -0.10681923 -0.47908437 -0.61089506  1.07641111  1.46134309]]


In [70]:
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [71]:
arr[0]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
arr[0,0]

array([0, 1, 2, 3])

In [73]:
arr[1,0,2]

10

In [74]:
arr.transpose((0,2,1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [75]:
x

array([[1, 2],
       [3, 4]])

In [76]:
v

array([ 9, 10])

In [77]:
y

array([[5, 6],
       [7, 8]])

In [78]:
x*y

array([[ 5, 12],
       [21, 32]])

In [79]:
x = np.array([[1,2],[3,4]])

In [80]:
np.sum(x)

10

In [81]:
x.sum()

10

In [82]:
print(np.sum(x,axis = 0))

[4 6]


In [83]:
print(np.mean(x))

2.5


In [84]:
print(np.sum(x,axis = 1))

[3 7]


In [85]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [86]:
arr.sort()

In [87]:
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [88]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [89]:
arr.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [91]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])