In [9]:
from numpy import *

In [10]:
random.rand(4,4)

array([[ 0.3752502 ,  0.51558345,  0.9015341 ,  0.20386815],
       [ 0.12964667,  0.04356876,  0.71418867,  0.7305    ],
       [ 0.65962738,  0.15665344,  0.33140669,  0.71881665],
       [ 0.14726679,  0.61325801,  0.6688412 ,  0.97984551]])

In [11]:
randMat = mat(random.rand(4,4))
randMat.I

matrix([[ 2.57171503, -2.04816372, -0.84513589, -0.45762611],
        [ 1.84872529, -0.09262054, -1.28315983, -1.65577944],
        [-3.31912762,  2.56987831,  2.50311064,  0.16372677],
        [-0.98152919,  0.57081824,  0.41435414,  1.58553415]])

In [13]:
InvRandMat = randMat.I
InvRandMat * randMat

matrix([[  1.00000000e+00,   7.63278329e-17,   1.77809156e-16,
          -3.33066907e-16],
        [  2.77555756e-16,   1.00000000e+00,   3.62557206e-16,
           4.44089210e-16],
        [ -1.80411242e-16,  -1.24900090e-16,   1.00000000e+00,
          -3.33066907e-16],
        [ -5.55111512e-17,  -5.55111512e-17,  -1.04083409e-16,
           1.00000000e+00]])

In [14]:
myEye = eye(4)
myEye

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])